### ISSUE TITLE
setting JAVA_TOOL_OPTIONS is required before mvn build package

### ISSUE THREAD

**Issue by matlads** [mapcode-foundation/mapcode-rest-service#24]
I got this building

`
Reason: The system default encoding must be UTF-8 (add '-Dfile.encoding=UTF-8' the JVM command line). Current value=US-ASCII
`

The solution was to execute the following before building

`
export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"
`

Maybe the build pipeline could be adjusted to include this?

**Comment by rijnb** [comment]
Thanks!
The Maven POM already included:

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

But in rare cases a command-line build might still fail indeed. I've added a comment to the README to instruct people to add `export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"` to their `.profile` or `.bashrc`.

And the build system, the Travis build YAML file is updated to include this as well.
Assuming this addresses your issue sufficiently, I close it. Re-open if I missed something please.
